"""inital tables

Revision ID: 29b4eaec2f74
Revises: 
Create Date: 2026-04-09 20:45:38.166509

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29b4eaec2f74'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ENDED', 'SCHEDULED', name='campaignstatus', native_enum=False), nullable=False),
    sa.Column('performance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaigns_status', 'campaigns', ['status'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='incidentstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_created_at', 'incidents', ['created_at'], unique=False)
    op.create_index('ix_incidents_status', 'incidents', ['status'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('RESTOCK', 'RUN_DISCOUNT', 'PAUSE_CAMPAIGN', 'CREATE_SUPPORT_TICKET', name='actiontype', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'EXECUTED', name='actionstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_actions_created_at', 'actions', ['created_at'], unique=False)
    op.create_index('ix_actions_incident_id', 'actions', ['incident_id'], unique=False)
    op.create_index('ix_actions_status', 'actions', ['status'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['inventory.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_date', 'sales', ['date'], unique=False)
    op.create_index('ix_sales_product_id', 'sales', ['product_id'], unique=False)
    op.create_index('ix_sales_region', 'sales', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_region', table_name='sales')
    op.drop_index('ix_sales_product_id', table_name='sales')
    op.drop_index('ix_sales_date', table_name='sales')
    op.drop_table('sales')
    op.drop_index('ix_actions_status', table_name='actions')
    op.drop_index('ix_actions_incident_id', table_name='actions')
    op.drop_index('ix_actions_created_at', table_name='actions')
    op.drop_table('actions')
    op.drop_table('inventory')
    op.drop_index('ix_incidents_status', table_name='incidents')
    op.drop_index('ix_incidents_created_at', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_campaigns_status', table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
