"""Business-rule engine — DEPRECATED.

Action recommendations are now generated by domain agents via request_* MCP
tools instead of hardcoded threshold rules.  This module is kept as an empty
placeholder so existing imports (if any) don't break at import time.
"""
